# 
msgid ""
msgstr ""
"Project-Id-Version: keystonemiddleware VERSION\n"
"Report-Msgid-Bugs-To: https://bugs.launchpad.net/openstack-i18n/\n"
"POT-Creation-Date: 2021-03-18 03:14+0000\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"PO-Revision-Date: \n"
"Last-Translator: \n"
"Language-Team: Russian\n"
"Language: ru\n"
"X-Generator: Zanata 4.3.3\n"
"Plural-Forms: nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && "
"n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2)\n"

#: keystonemiddleware/ec2_token.py:126
msgid "Signature not provided"
msgstr ""

#: keystonemiddleware/ec2_token.py:130
msgid "Access key not provided"
msgstr ""

#: keystonemiddleware/ec2_token.py:185
#, python-format
msgid "Error response from keystone: %s"
msgstr ""

#: keystonemiddleware/ec2_token.py:191
msgid "Failure parsing response from keystone"
msgstr ""

#: keystonemiddleware/auth_token/__init__.py:438
#: keystonemiddleware/auth_token/__init__.py:451
#: keystonemiddleware/auth_token/__init__.py:486
#: keystonemiddleware/auth_token/__init__.py:561
#: keystonemiddleware/auth_token/__init__.py:575
#: keystonemiddleware/auth_token/__init__.py:589
#: keystonemiddleware/auth_token/_identity.py:163
msgid "Token authorization failed"
msgstr ""

#: keystonemiddleware/auth_token/__init__.py:680
msgid "The request you have made requires authentication."
msgstr ""

#: keystonemiddleware/auth_token/__init__.py:786
msgid "Unable to determine service tenancy."
msgstr ""

#: keystonemiddleware/auth_token/_auth.py:135
msgid "Invalid version asked for in auth_token plugin"
msgstr ""

#: keystonemiddleware/auth_token/_cache.py:272
msgid ""
"memcache_secret_key must be defined when a memcache_security_strategy is "
"defined"
msgstr ""

#: keystonemiddleware/auth_token/_identity.py:58
#: keystonemiddleware/auth_token/_identity.py:179
msgid "Failed to fetch token data from identity server"
msgstr ""

#: keystonemiddleware/auth_token/_identity.py:139
msgid "No compatible apis supported by server"
msgstr ""

#: keystonemiddleware/auth_token/_identity.py:170
msgid "Identity server rejected authorization necessary to fetch token data"
msgstr ""

#: keystonemiddleware/auth_token/_memcache_crypt.py:164
msgid "Encrypted data appears to be corrupted."
msgstr ""

#: keystonemiddleware/auth_token/_memcache_crypt.py:208
msgid "Invalid MAC; data appears to be corrupted."
msgstr ""

