# Andreas Jaeger <jaegerandi@gmail.com>, 2016. #zanata
msgid ""
msgstr ""
"Project-Id-Version: oslo.versionedobjects VERSION\n"
"Report-Msgid-Bugs-To: https://bugs.launchpad.net/openstack-i18n/\n"
"POT-Creation-Date: 2021-08-10 14:54+0000\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"PO-Revision-Date: 2016-04-12 06:51+0000\n"
"Last-Translator: Copied by Zanata <copied-by-zanata@zanata.org>\n"
"Language-Team: Russian\n"
"Language: ru\n"
"X-Generator: Zanata 4.3.3\n"
"Plural-Forms: nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && "
"n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2)\n"

#: oslo_versionedobjects/base.py:601
#, python-format
msgid "Cannot load '%s' in the base class"
msgstr ""

#: oslo_versionedobjects/base.py:609
msgid "Cannot save anything in the base class"
msgstr ""

#: oslo_versionedobjects/base.py:681
#, python-format
msgid "%(objname)s object has no attribute '%(attrname)s'"
msgstr ""

#: oslo_versionedobjects/exception.py:103
msgid "An unknown exception occurred."
msgstr "Обнаружено неизвестное исключение."

#: oslo_versionedobjects/exception.py:143
#, python-format
msgid "Object action %(action)s failed because: %(reason)s"
msgstr "Действие объекта %(action)s не выполнено, причина: %(reason)s"

#: oslo_versionedobjects/exception.py:147
#, python-format
msgid "Field %(field)s of %(objname)s is not an instance of Field"
msgstr "Поле %(field)s объекта %(objname)s не является экземпляром Field"

#: oslo_versionedobjects/exception.py:151
#, python-format
msgid "Cannot call %(method)s on orphaned %(objtype)s object"
msgstr "Невозможно вызвать %(method)s в неприсвоенном объекте %(objtype)s"

#: oslo_versionedobjects/exception.py:155
#, python-format
msgid ""
"Version %(objver)s of %(objname)s is not supported, supported version is "
"%(supported)s"
msgstr ""

#: oslo_versionedobjects/exception.py:160
#, python-format
msgid "Cannot modify readonly field %(field)s"
msgstr "Нельзя изменить поле %(field)s, доступное только для чтения"

#: oslo_versionedobjects/exception.py:164
#, python-format
msgid "Unsupported object type %(objtype)s"
msgstr "Неподдерживаемый тип объекта %(objtype)s"

#: oslo_versionedobjects/exception.py:168
msgid "Enum fields require a list of valid_values"
msgstr ""

#: oslo_versionedobjects/exception.py:172
msgid "Enum valid values are not valid"
msgstr ""

#: oslo_versionedobjects/exception.py:176
#, python-format
msgid "%(typename)s in %(fieldname)s is not an instance of Enum"
msgstr "%(typename)s в %(fieldname)s не является экземпляром Enum"

#: oslo_versionedobjects/exception.py:180
#, python-format
msgid "%(fieldname)s missing field type"
msgstr "Отсутствует тип поля %(fieldname)s"

#: oslo_versionedobjects/exception.py:184
#, python-format
msgid "Invalid target version %(version)s"
msgstr ""

#: oslo_versionedobjects/exception.py:188
#, python-format
msgid "No subobject existed at version %(target_version)s"
msgstr ""

#: oslo_versionedobjects/exception.py:192
#, python-format
msgid ""
"%(child_objname)s is referenced by %(parent_objname)s but is not registered"
msgstr ""

#: oslo_versionedobjects/fields.py:37
#, python-format
msgid "Key %(key)s must be of type %(expected)s not %(actual)s"
msgstr ""

#: oslo_versionedobjects/fields.py:47
#, python-format
msgid "Element %(key)s:%(val)s must be of type %(expected)s not %(actual)s"
msgstr ""

#: oslo_versionedobjects/fields.py:180
#, python-format
msgid "Field `%s' cannot be None"
msgstr ""

#: oslo_versionedobjects/fields.py:271
#, python-format
msgid "A string is required in field %(attr)s, not a %(type)s"
msgstr ""

#: oslo_versionedobjects/fields.py:299
#, python-format
msgid "Version %(val)s is not a valid predicate in field %(attr)s"
msgstr ""

#: oslo_versionedobjects/fields.py:324 oslo_versionedobjects/fields.py:330
#, python-format
msgid "Field value %s is invalid"
msgstr ""

#: oslo_versionedobjects/fields.py:345
#, python-format
msgid "%s has no pattern"
msgstr ""

#: oslo_versionedobjects/fields.py:392
#, python-format
msgid "Malformed MAC %s"
msgstr ""

#: oslo_versionedobjects/fields.py:406
#, python-format
msgid "Malformed PCI address %s"
msgstr ""

#: oslo_versionedobjects/fields.py:423 oslo_versionedobjects/fields.py:443
#, python-format
msgid "Value must be >= 0 for field %s"
msgstr ""

#: oslo_versionedobjects/fields.py:476
#, python-format
msgid "A datetime.datetime is required in field %(attr)s, not a %(type)s"
msgstr ""

#: oslo_versionedobjects/fields.py:525 oslo_versionedobjects/fields.py:539
#: oslo_versionedobjects/fields.py:553
#, python-format
msgid "Network \"%(val)s\" is not valid in field %(attr)s"
msgstr "Недопустимая сеть \"%(val)s\" в поле %(attr)s"

#: oslo_versionedobjects/fields.py:650
#, python-format
msgid "A list is required in field %(attr)s, not a %(type)s"
msgstr ""

#: oslo_versionedobjects/fields.py:675
#, python-format
msgid "A dict is required in field %(attr)s, not a %(type)s"
msgstr ""

#: oslo_versionedobjects/fields.py:741
#, python-format
msgid "A set is required in field %(attr)s, not a %(type)s"
msgstr ""

#: oslo_versionedobjects/fields.py:804
#, python-format
msgid ""
"An object of type %(type)s is required in field %(attr)s, not a %(valtype)s"
msgstr ""

#: oslo_versionedobjects/fields.py:1014
#, python-format
msgid ""
"%(object)s.%(name)s is not allowed to transition out of %(value)s state"
msgstr ""

#: oslo_versionedobjects/fields.py:1027
#, python-format
msgid ""
"%(object)s.%(name)s is not allowed to transition out of '%(current_value)s' "
"state to '%(value)s' state, choose from %(options)r"
msgstr ""

